### ISSUE TITLE
OCR0047: Chuyik Data Preparation

### ISSUE THREAD

**Issue by ta4tsering** [OpenPecha/ocr_handwriting_aligner#12]
## Description:
So we have scanned pages that contains handwritten Tibetan cursive by annotators, and @tenzin3 has worked on script that will use the scanned page images to determine with lines are valid and which lines are in-valid. We need all the cursive data in line images and its transcriptions.

## Resources:
Previously worked Ticket: https://github.com/orgs/OpenPecha/projects/56/views/7?pane=issue&itemId=58487503

Scanned Images Directory: 
    - [potrait](https://drive.google.com/drive/folders/1xUnktrh_ie0o-5vH_Grk8KN4rRl9uy0H)
    - [landscape](https://drive.google.com/drive/folders/16FEH5m2Xu0TcX-JYNwc0iuuAaUaw1rLx)
    - [transcripts](https://drive.google.com/drive/folders/1ht0x3Ff86yDrsKKpQAi1I7prWnFH33Vt)

## Completion Criteria:
all the valid lines, each line image cropped separately and its transcription in the csv file

## Expected Workflow:

![Image](https://github.com/user-attachments/assets/06fdfbeb-8b20-445d-bb6a-7b7ab3234f23)

## Subtasks:

- [x] start by downloading the dataset provided
- [x] clone the repo and create a separate branch to make changes on
- [x] convert the pdf to jpg
- [x] get bounding positions for both portrait and landscape
- [x] crop the images according to the position
- [x] classify if the image has valid line or not
- [x] save it as a csv file 

Started working on this task from 26th August, 2024
Estimate to finish it in around 2 - 3 days (from 29th August, 2024) , so End Date will be on 31st August, 2024 for now.

**Comment by tenzinchoedon** [comment]
Below is how the image are looking after cropping of line and label 

Line image:

![Image](https://github.com/user-attachments/assets/9c582622-b1ef-4efa-968c-f3873a8c8ea8)

Label image:

![Image](https://github.com/user-attachments/assets/0137412d-a969-46ec-843c-93d89c4590d1)

**Comment by tenzinchoedon** [comment]
Getting an error while printing the transcript in the final output csv file

outputcsv file:

![Image](https://github.com/user-attachments/assets/0899a55f-74cf-4d3b-8977-04cc3d8f024f)

transcript print separately:

![Image](https://github.com/user-attachments/assets/bef6c3b0-ca4e-485a-b276-94801d715f65)

**Comment by ta4tsering** [comment]
in your image_url the P000011 images are in P000010's directory and try opening the csv in vscode or in google sheet or something to see if the transcripts are there or not.
